"""add password hash

Revision ID: 518c42341254
Revises: a1635d2f5183
Create Date: 2025-11-12 01:12:07.495080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '518c42341254'
down_revision: Union[str, Sequence[str], None] = 'a1635d2f5183'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student')
    op.add_column('users', sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    op.create_table('student',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('total_marks', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_sub', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('average', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('grade', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('update_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('student_pkey'))
    )
    # ### end Alembic commands ###
