"""rename update_at to updated_at

Revision ID: ddfd2c42f1de
Revises: 632ed83e8121
Create Date: 2025-11-20 21:40:29.502839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ddfd2c42f1de'
down_revision: Union[str, Sequence[str], None] = '632ed83e8121'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=True))
    op.drop_column('reviews', 'update_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('update_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('reviews', 'updated_at')
    # ### end Alembic commands ###
